### PR TITLE
Addverbosityandaltersettings

### LINKED ISSUE #17: Convert Constants to a single Settings Object
Each possible Configuration or Constants should be grouped up into a single Custom Object.
For Example
```ps1
# Define constants
$TmpDir = "_tmp"
$SiteDir = "_site"
```
Should be this
```ps1
$Settings = [PSCustomObject] @{
  TempDir = "_tmp"
  SiteDir = "_site"
}
```
Accessing the Variables would be like this
```ps1
$Settings.TempDir
```
Windows uses as Standard the "temp" wording, linux uses the wording "tmp"

i would either drag other settings into the Settings variable or make a second one for "Configuration" e.g.
the String 'languages.json' is only used one time but plays a significant role in the usage of the script.
it would be better to add it to the Settings so another user can use his custom location of his settings.json
The user can then alter the settings without knowing how the file is actually treated, also i would change it to a relative path to make the usage more precise e.g.
```ps1
$Settings = [PSCustomObject] @{
    TmpDir = "_tmp"
    SiteDir = "_site"
    LanguageFile =".\languages.json"
}
```
And the usage would look like 
`return Get-Content $Settings.LanguageFile -Encoding UTF8 | ConvertFrom-Json`
now there is no "magic string" anymore in this line.
I do not count prompts or messages as magic strings, but for parameters or values that play a significant role, its better this way

Also i would include the "build.log" string into the settings e.g.
```ps1
$Settings = [PSCustomObject] @{
    TmpDir = "_tmp"
    SiteDir = "_site"
    LanguageFile =".\languages.json"
    LogPath = ".\build.log"
}
and usage would be 
`Start-Transcript -Path $Settings.LogPath`
```

### LINKED ISSUE #31: Add Verbosity
For the Transcript it helps to track back what happened if more statements give results.
Here it would be appropriate to add verbosity
```ps1
        Remove-Item en/api/*yml -recurse
        Remove-Item en/api/.manifest
```
should be
```ps1
        Remove-Item en/api/*yml -recurse -Verbose
        Remove-Item en/api/.manifest -Verbose
```

### LINKED ISSUE #35: Forgotten /manual
`Write-Host -ForegroundColor Yellow "Warning: $($SelectedLanguage.language)/manual not found."`

and 
`$posts = Get-ChildItem $langFolder/manual/*.md -Recurse -Force`

should use the new `$Settings.ManualFolderName`
else it would result in a bug when the folder name gets changed

### PR DESCRIPTION
**Pull request by IXLLEGACYIXL**
Puts everything into the Settings Object
Added Verbosity to some Statements for better logs

Needs Testing 
Fixes #31 
Fixes #17
Fixes #35

### CODE REVIEW

**Comment by IXLLEGACYIXL** [comment]
Fixes #35

**Comment by VaclavElias** [comment]
This looks nice, I will merge it and test it tomorrow :)

**Comment by IXLLEGACYIXL** [comment]
if you want, you can add more "magic" strings to the settings but these were the more important ones that i found. For a future enhancement

**Review by VaclavElias — APPROVED** [review]
Thank you @IXLLEGACYIXL

**Pull request merged**
